#!/usr/bin/env python3
"""
buildweb.py - inline web/index.html, web/app.css and web/app.js (plus any
              sorted view-*.css and view-*.js) into one HTML page, strip
              comments and leading whitespace, gzip it and write a C header
              the firmware includes as its embedded web GUI.

usage: buildweb.py <webdir> <out.h>

Invector Embedded Systems AB
"""

import gzip
import hashlib
import re
import sys
from pathlib import Path

MAX_GZ_BYTES = 49152
CSS_MARKER = "<!-- CSS -->"
JS_MARKER = "<!-- JS -->"


def strip_css_comments(text):
    """Remove /* ... */ comments from CSS, across lines."""
    return re.sub(r"/\*.*?\*/", "", text, flags=re.DOTALL)


def strip_js_comments(text):
    """Remove full-line // comments from JS: only lines whose first
    non-space characters are //."""
    out_lines = []
    for line in text.splitlines():
        if line.lstrip().startswith("//"):
            continue
        out_lines.append(line)
    return "\n".join(out_lines)


def strip_html_comments(text):
    """Remove <!-- ... --> comments from HTML, across lines."""
    return re.sub(r"<!--.*?-->", "", text, flags=re.DOTALL)


def strip_leading_ws(text):
    """Strip leading whitespace on every line."""
    return "\n".join(line.lstrip() for line in text.splitlines())


def read_stripped(path, stripper):
    text = path.read_text(encoding="utf-8")
    return stripper(text)


def build_page(webdir):
    """Read webdir/index.html and inline the CSS and JS markers, returning
    the final HTML page as a string. Shared with mockserver.py so the mock
    serves the exact page the device would."""
    webdir = Path(webdir)
    html = (webdir / "index.html").read_text(encoding="utf-8")

    css_files = [webdir / "app.css"] + sorted(webdir.glob("view-*.css"))
    js_files = [webdir / "app.js"] + sorted(webdir.glob("view-*.js"))

    css_parts = []
    for f in css_files:
        if f.exists():
            css_parts.append(read_stripped(f, strip_css_comments))
    css_blob = "<style>" + "\n".join(css_parts) + "</style>"

    js_parts = []
    for f in js_files:
        if f.exists():
            js_parts.append(read_stripped(f, strip_js_comments))
    js_blob = "<script>" + "\n".join(js_parts) + "</script>"

    if CSS_MARKER not in html:
        raise ValueError("index.html is missing the %s marker" % CSS_MARKER)
    if JS_MARKER not in html:
        raise ValueError("index.html is missing the %s marker" % JS_MARKER)

    html = html.replace(CSS_MARKER, css_blob)
    html = html.replace(JS_MARKER, js_blob)

    html = strip_html_comments(html)
    html = strip_leading_ws(html)

    return html


def write_header(out_path, raw_bytes, gz_bytes):
    etag = hashlib.sha1(gz_bytes).hexdigest()[:8]

    lines = []
    lines.append("// Generated by tools/buildweb.py, do not edit.")
    lines.append('#define WEBUI_ETAG "\\"%s\\""' % etag)
    lines.append("static const size_t WEBUI_GZ_LEN = %d;" % len(gz_bytes))
    lines.append("static const uint8_t WEBUI_GZ[] PROGMEM = {")

    for i in range(0, len(gz_bytes), 16):
        chunk = gz_bytes[i:i + 16]
        hex_bytes = ", ".join("0x%02x" % b for b in chunk)
        lines.append("    " + hex_bytes + ",")

    lines.append("};")
    lines.append("")

    out_path.write_text("\n".join(lines), encoding="utf-8")


def main(argv):
    if len(argv) != 3:
        print("usage: buildweb.py <webdir> <out.h>", file=sys.stderr)
        return 1

    webdir = Path(argv[1])
    out_path = Path(argv[2])

    html = build_page(webdir)
    raw_bytes = html.encode("utf-8")
    gz_bytes = gzip.compress(raw_bytes, compresslevel=9, mtime=0)

    if len(gz_bytes) > MAX_GZ_BYTES:
        print(
            "buildweb: %d bytes gzipped exceeds the %d byte budget"
            % (len(gz_bytes), MAX_GZ_BYTES),
            file=sys.stderr,
        )
        return 1

    write_header(out_path, raw_bytes, gz_bytes)

    print("webui: %d bytes raw, %d bytes gzipped" % (len(raw_bytes), len(gz_bytes)))
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
